/**
 * Utility functions for exporting data.
 */

export const exportToMarkdown = (title: string, original: string, refined: string): string => {
  return `# ${title}

## Original Prompt
\`\`\`
${original}
\`\`\`

## Refined Prompt
\`\`\`
${refined}
\`\`\`

*Generated by Prompt Architect 2025*
`;
};

export const exportToJSON = (data: any): string => {
  return JSON.stringify(data, null, 2);
};

export const downloadFile = (content: string, fileName: string, contentType: string) => {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
};
